-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.etkinlik_gorevleri
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    etkinlikziyaretid integer,
    islemid integer,
    aciklama text COLLATE pg_catalog."default",
    tarih date,
    CONSTRAINT etkinlikgorevleri_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.etkinlik_gorevlileri
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    personelid integer,
    yetki character varying(30) COLLATE pg_catalog."default",
    etkinlikziyaretid integer,
    CONSTRAINT etkinlikgorevlileri_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.etkinlik_ziyaret
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    randevuid integer,
    aylikucret numeric,
    CONSTRAINT etkinlikziyaret_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.islemler
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    adi character varying(50) COLLATE pg_catalog."default",
    tip character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT islemler_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personel
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    adi character varying(25) COLLATE pg_catalog."default",
    soyadi character varying(25) COLLATE pg_catalog."default",
    telefon character varying(11) COLLATE pg_catalog."default",
    kayittarihi date,
    silinmedurumu boolean,
    silinmetarihi date,
    unvanid integer,
    CONSTRAINT personel_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.randevu
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    yurutucufirmaid integer,
    randevutarihi date,
    onay boolean,
    aciklama text COLLATE pg_catalog."default",
    CONSTRAINT randevu_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.unvan
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    unvanadi character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT unvan_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.yurutucu_firma
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    adi character varying(30) COLLATE pg_catalog."default",
    kayittarihi date,
    CONSTRAINT yurutucufirma_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.etkinlik_gorevleri
    ADD CONSTRAINT etkinlikgorevleri_etkinlikid_fkey FOREIGN KEY (etkinlikziyaretid)
    REFERENCES public.etkinlik_ziyaret (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.etkinlik_gorevleri
    ADD CONSTRAINT etkinlikgorevleri_islemid_fkey FOREIGN KEY (islemid)
    REFERENCES public.islemler (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.etkinlik_gorevlileri
    ADD CONSTRAINT etkinlik_gorevlileri_etkinlikziyaretid_fkey FOREIGN KEY (etkinlikziyaretid)
    REFERENCES public.etkinlik_ziyaret (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.etkinlik_gorevlileri
    ADD CONSTRAINT etkinlikgorevlileri_personelid_fkey FOREIGN KEY (personelid)
    REFERENCES public.personel (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.etkinlik_ziyaret
    ADD CONSTRAINT etkinlikziyaret_randevuid_fkey FOREIGN KEY (randevuid)
    REFERENCES public.randevu (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.personel
    ADD CONSTRAINT personel_unvanid_fkey FOREIGN KEY (unvanid)
    REFERENCES public.unvan (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.randevu
    ADD CONSTRAINT randevu_yurutucufirmaid_fkey FOREIGN KEY (yurutucufirmaid)
    REFERENCES public.yurutucu_firma (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;